# Generated by Django 3.0.6 on 2020-05-31 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trajectory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_position', models.CharField(max_length=64)),
                ('receive_position', models.CharField(max_length=64)),
                ('trajectory', models.CharField(max_length=255)),
                ('trajectory_id', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('divice_id', models.CharField(max_length=64)),
                ('divice_position', models.CharField(max_length=64)),
                ('send_message_text', models.CharField(max_length=256)),
                ('receive_message_text', models.CharField(max_length=256)),
                ('trajectory_id', models.CharField(max_length=64)),
                ('send_time', models.DateTimeField()),
            ],
        ),
    ]
