# Generated by Django 3.0.6 on 2020-05-31 06:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('windletterapi', '0003_auto_20200531_0606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trajectory',
            name='receive_position',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='trajectory',
            name='send_position',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='trajectory',
            name='trajectory',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='trajectory',
            name='trajectory_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='user',
            name='divice_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='user',
            name='divice_position_lat',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='user',
            name='divice_position_lon',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='user',
            name='receive_message_text',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='user',
            name='send_message_text',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='user',
            name='send_time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='user',
            name='trajectory_id',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
