# Generated by Django 3.0.6 on 2020-05-31 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('windletterapi', '0004_auto_20200531_0654'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='divice_position_lat',
            new_name='divice_position',
        ),
        migrations.RemoveField(
            model_name='user',
            name='divice_position_lon',
        ),
    ]
